import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/UI/Header";
import NavBar from "@/components/NavBar";


const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "istee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <div className="max-w-[520px] w-full m-auto  bg-black ">
          <Header />
          {children}
          <NavBar />
        </div>
      </body>
    </html>
  );
}
